bot:
  botName: ${BOT_NAME}
  botToken: ${BOT_TOKEN}
  sheetId: ${SHEET_ID}
  apiKey: ${API_KEY}
  sheetName: subs
  range: A1:A10
spring:
  config:
    import: optional:file:.env[.properties]
  main:
    web-application-type: NONE
cache:
  expireTime: 60